name: Deploy Documentation

on:
  push:
    tags:
      - 'v*'      # versioned builds (e.g., v1.0.0)
    # branches:
    #   - release      # build latest docs from main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for git tags and branches

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-multiversion sphinx-rtd-theme

      - name: Build documentation with Sphinx Multiversion
        run: |
          sphinx-multiversion Doc/source Doc/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Doc/_build/html
          publish_branch: gh-pages


